-- =============================================================================
-- Migration 002: baseline_schema (Prisma-managed)
-- =============================================================================
--
-- DO NOT run this file manually.
-- This migration is generated and applied by Prisma:
--
--   npx prisma migrate dev --name baseline_schema
--
-- Prisma reads prisma/schema.prisma and generates the full DDL for all tables,
-- enums, foreign keys, and standard indexes declared in the schema.
--
-- After this runs, apply migration 003 (partial indexes) manually in Supabase
-- SQL editor before any application code runs.
--
-- Verify success:
--   npx prisma studio
--   All tables listed in schema.prisma should be visible with correct columns.
--
-- =============================================================================
